```{r}
#install.packages('tidyverse')
#install.packages('DataExplorer')
```
```{r Library}
library(corrplot)
library(ggplot2)
library(DataExplorer)
library(e1071)
library(caret)
```
```{r read date}
date <- read.csv("glass.csv", header = TRUE)
```

```{r view date}
View(date)
date
```

```{r show num column}
colnum <- ncol(date)
print(paste("num of col : ", ncol(date)))
```

```{r show number row}
rownum <- nrow(date)
print(paste("num of row : ", nrow(date)))
```

```{r show name column}
print(colnames(date))
```

```{r show struachre date }
str(date)
```

```{r show summary date}
summary(date)
```

```{r show plot missing date beffor replace value}
png("beffor_del.png");
plot_missing(date)
```

```{r replace 0 value to null value and show}
png("missing_value_after process.png")
date[date==0]<- NA
plot_missing(date, geom_label_args = list("size" = 4),title = "Missing Data in Glass",theme_config = list(legend.position =c("top")))
```

```{r}
date<-date[,-8:-9]
date[is.na(date)]<- 0
date
```

```{r}
png("after_del.png");
plot_missing(date)
```
```{r}
table(date$Type)
```

```{r}
date$Type <-as.factor(date$Type)
str(date)
```

```{r}
#png("corplot_process.png")
corrplot(cor(date[,-8]))
```

```{r}
png("boxplot_Type_with_RI.png")
boxplot(date$RI~date$Type,main ="Types of glass and the severity of its refraction",xlab = 'Type',ylab = 'RI')
```

```{r}
png("barplot.png")
dateElemn<-date[,-8]
dateElemn<-dateElemn[,-1]
sum_col<- apply(dateElemn, 2, mean)
barplot(sum_col,col ='red',main = 'average of items used' )
```

```{r}
png("plot.png")
plot(dateElemn,main ="relation  elements " )
```

```{r}
png("na_type.png")
ggplot(date, aes(x=Na, fill=Type,colour =Type)) + geom_density(alpha = 0.1)
```

```{r}
png("mg_type.png")
ggplot(date, aes(x=Mg, fill=Type,colour =Type)) + geom_density(alpha = 0.1)
```

```{r}
png("al_type.png")
ggplot(date, aes(x=Al, fill=Type,colour =Type)) + geom_density(alpha = 0.1)
```

```{r}
png("si_type.png")
ggplot(date, aes(x=Si, fill=Type,colour =Type)) + geom_density(alpha = 0.1)
```

```{r}
png("k_type.png")
ggplot(date, aes(x=K, fill=Type,colour =Type)) + geom_density(alpha = 0.1)
```

```{r}
png("ca_type.png")
ggplot(date, aes(x=Ca, fill=Type,colour =Type)) + geom_density(alpha = 0.1)
```

```{r}
clusters <- kmeans(date$RI, 9)
clusters 
```
```{r}
date$RIcluster <- clusters$cluster
corrplot(cor(date[,-8]))
date$RIcluster <- as.factor(date$RIcluster)
date
```

```{r}
png("Na_RIcluster.png");
ggplot(date, aes(x=Na, fill=RIcluster,colour =RIcluster)) + geom_density(alpha = 0.1)
```
```{r}
png("Mg_RIcluster.png");
ggplot(date, aes(x=Mg, fill=RIcluster,colour =RIcluster)) + geom_density(alpha = 0.1)
```

```{r}
png("AL_RIcluster.png");
ggplot(date, aes(x=Al, fill=RIcluster,colour =RIcluster)) + geom_density(alpha = 0.1)
```

```{r}
png("Si_RIcluster.png");
ggplot(date, aes(x=Si, fill=RIcluster,colour =RIcluster)) +geom_density(alpha = 0.1)
```

```{r}
png("K_RIcluster.png");
ggplot(date, aes(x=K, fill=RIcluster,colour =RIcluster)) + geom_density(alpha = 0.1)
```

```{r}
png("Ca_RIcluster.png");
ggplot(date, aes(x=Ca, fill=RIcluster,colour =RIcluster)) + geom_density(alpha = 0.1)
```

```{r}
png("boxplot_Type_with_RIcluster.png")
boxplot(as.numeric(date$RIcluster)~date$Type,main ="Types of glass and the severity of its refraction",xlab = 'Type',ylab = 'RIcluster')
```

```{r}
index <- createDataPartition(y = date$RIcluster, p = 0.7, list = F)
trainDate <- date[index,]
testDate <- date[-index,]
dim(date)
dim(trainDate)
dim(testDate)

```

```{r}
table(date$RIcluster)
table(trainDate$RIcluster)
table(testDate$RIcluster)
```

```{r}
traincontrol <- trainControl(method = "cv", number = 10)
```

```{r}
trainRIGlmnet <- train(RIcluster~., trainDate, method = "glmnet", metric = "Accuracy",
                       tuneGrid = expand.grid(alpha = 0.1, lambda = 0.004972569),trControl = traincontrol)
PredictRIClusetrGlmnet <- predict(trainRIGlmnet, testDate)
confusionMatrix(testDate$RIcluster, PredictRIClusetrGlmnet)
```

```{r}
trainRISvmRadial <- train(RIcluster~., trainDate, method = "svmRadial", preProcess = c("center","scale")
                          ,metric = "Accuracy",tuneGrid = expand.grid(.sigma = 0.5, .C = 10)
                          ,trControl = traincontrol)
PredictRIClusetrSvmRadial <- predict(trainRISvmRadial, testDate)
confusionMatrix(testDate$RIcluster, PredictRIClusetrSvmRadial)
```

```{r}
trainRIRf <- train(RIcluster~., trainDate, method = 'rf',metric = "Accuracy",ntree = 500
                   ,tuneGrid = expand.grid(.mtry = 2:8),trControl = traincontrol)
PredictRIClusetrRf <- predict(trainRIRf, testDate)
confusionMatrix(testDate$RIcluster, PredictRIClusetrRf)
```

```{r}
trainRINnet <- train(RIcluster~., trainDate, method = 'nnet',metric = "Accuracy"
                     ,preProcess = c("center","scale"),tuneGrid = expand.grid(size = 10, decay = 0.1)
                     ,verbose = F, trControl = traincontrol)
PredictRIClusetrNnet <- predict(trainRINnet, testDate)
confusionMatrix(testDate$RIcluster, PredictRIClusetrNnet)
```
```{r}
modelResamples <- resamples(list(MLR = trainRIGlmnet, SVM = trainRISvmRadial, RF = trainRIRf,NNet = trainRINnet))
```

```{r}
png("bwplot_Kappa_Accuracy.png")
bwplot(modelResamples, metric = c("Kappa", "Accuracy"))
```

```{r}
png("densityplot_Kappa_Accuracy.png")
densityplot(modelResamples, metric = c("Kappa", "Accuracy"), auto.key = list(coloumns = 3))
```

